name: LokiAI Rebalancer

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main           # run on push to main branch

jobs:
  run-executor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file from GitHub Secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run LokiAI Executor
        run: python -m agents.portfolio_rebalancer.executor
